name: CodeceptJS Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies (Vite, Nodemon)
        run: npm install

      - name: Install test dependencies
        run: |
          cd test
          npm install

      - name: Start Vite + Nodemon and run tests
        run: |
          npm run dev > vite.log 2>&1 &
          npx nodemon index.js > nodemon.log 2>&1 &
          sleep 5
          cd test
          npx codeceptjs run
